services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=solar_db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ..:/app
    ports:
      - "5432:5432"

  flask:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0"]

  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ../frontend:/app/frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - flask

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  timescaledb_data:
  pgadmin_data: