version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=solar_db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - .:/app
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile  # Assume you create one for FastAPI
    volumes:
      - .:/app
    depends_on:
      - timescaledb
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend  # Assume frontend folder
    ports:
      - "3000:3000"
    command: ["npm", "run","dev"]
    depends_on:
      - fastapi

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:2.7.0
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:password@timescaledb:5432/airflow
    volumes:
      - ./backend/airflow/dags:/opt/airflow/dags
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
  pgadmin_data: